# Generated by Django 2.2 on 2021-05-11 17:45

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210511_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinecenter',
            old_name='mlf',
            new_name='mfl',
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SubCounty'),
        ),
    ]
