# Generated by Django 2.2 on 2021-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210511_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'counties'},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name_plural': 'sub-counties'},
        ),
        migrations.AlterModelOptions(
            name='vaccinecenter',
            options={'verbose_name_plural': 'vaccine centers'},
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='mfl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinecenter',
            name='ownership',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('millitary', 'Millitary'), ('fbo', 'FBO'), ('ngo', 'NGO'), ('armed_forces', 'Armed Forces')], default='public', max_length=50, null=True),
        ),
    ]
